"""add_resolved_at_to_tickets

Revision ID: 1e20803a61b8
Revises: 15107cde5f31
Create Date: 2026-05-17 16:54:48.644303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e20803a61b8'
down_revision: Union[str, Sequence[str], None] = '15107cde5f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'resolved_at')
    # ### end Alembic commands ###
