"""add_sla_fields

Revision ID: 620076afd572
Revises: af70f505f73e
Create Date: 2026-05-29 19:26:00.355022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620076afd572'
down_revision: Union[str, Sequence[str], None] = 'af70f505f73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.add_column('tickets', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('sla_breached', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    
    # Backfill due_at for existing tickets using their creation time + priority mapping
    op.execute(
        """
        UPDATE tickets
        SET due_at = CASE
            WHEN CAST(priority AS VARCHAR) = 'low' THEN created_at + INTERVAL '48 hours'
            WHEN CAST(priority AS VARCHAR) = 'medium' THEN created_at + INTERVAL '24 hours'
            WHEN CAST(priority AS VARCHAR) = 'high' THEN created_at + INTERVAL '12 hours'
            WHEN CAST(priority AS VARCHAR) = 'urgent' THEN created_at + INTERVAL '4 hours'
            ELSE created_at + INTERVAL '24 hours'
        END
        WHERE due_at IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.drop_column('tickets', 'sla_breached')
    op.drop_column('tickets', 'due_at')
    op.alter_column('teams', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    # ### end Alembic commands ###
